# Generated by Django 2.2.5 on 2019-10-04 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=120, null=True)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=120, null=True)),
                ('criacao', models.DateField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_g1.Departamento')),
                ('intere', models.ManyToManyField(related_name='interesados', to='app_g1.Pessoa')),
                ('inves', models.ManyToManyField(related_name='investigados', to='app_g1.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_g1.Pessoa')),
                ('matricula', models.CharField(max_length=15)),
                ('data_admissao', models.DateField()),
            ],
            bases=('app_g1.pessoa',),
        ),
        migrations.CreateModel(
            name='PedidoPrazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_g1.Documento')),
                ('prazo_anterior', models.DateField()),
                ('novo_prazo', models.DateField()),
                ('justificativa', models.TextField(blank=True, null=True)),
            ],
            bases=('app_g1.documento',),
        ),
        migrations.CreateModel(
            name='Portaria',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_g1.Documento')),
                ('numero_portaria', models.CharField(blank=True, max_length=120, null=True)),
            ],
            bases=('app_g1.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField()),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='app_g1.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem', to='app_g1.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_g1.Processo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_g1.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to='app_g1.Funcionario'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_g1.Documento')),
                ('data_envio', models.DateField()),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_g1.Departamento')),
            ],
            bases=('app_g1.documento',),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_g1.Funcionario'),
        ),
    ]
